### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by SpodoY** [google-developer-training/basic-android-kotlin-compose-training-unscramble#77] opened 2023-03-27 08:08 UTC
In section 8 (Update score and word count), at task 5 the instructions say "Call it currentWordCount and initialize it to 1" but the code snipped has score set to 1 and currentWordCount to 0

![image](https://user-images.githubusercontent.com/72346498/227880022-9fe30707-f9b2-479a-8a19-97624a2befdf.png)

**Comment by SpodoY** [comment] 2023-03-28 12:14
Duplicate

**Comment by osuleymanova** [comment] 2023-04-04 18:51
Duplicate of #73, #69

**Comment by osuleymanova** [comment] 2023-05-31 23:23
Hello @SpodoY ,

Thank you for reaching out to us and reporting this typo. The code snippet is updated:

![Screenshot 2023-05-31 at 4 14 51 PM](https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/86437155/bf239f8d-d29a-42fe-98bc-3428e69d73b1)

**Closed by osuleymanova** 2023-05-31 23:23 UTC
