### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by rbinek** [google-developer-training/basic-android-kotlin-compose-training-unscramble#79] opened 2023-04-03 21:09 UTC
5.1pk should be Open build.gradle(Module: app) instead of Module: Unscramble

**Comment by osuleymanova** [comment] 2023-04-04 18:40
Hello @rbinek,

Thank you for reaching out to us. This typo will be fixed and republished soon.

**Closed by osuleymanova** 2023-04-04 18:40 UTC

**Comment by osuleymanova** [comment] 2023-04-04 19:03
Duplicate of #67
