### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by roumenh** [google-developer-training/basic-android-kotlin-compose-training-unscramble#61] opened 2023-02-20 17:22 UTC
<img width="738" alt="image" src="https://user-images.githubusercontent.com/5468334/220168944-00a7ad80-4e31-45d7-b575-9d70aa0191f2.png">
the score should be zero, the currentWordCount should be 1

**Comment by osuleymanova** [comment] 2023-03-16 22:09
Duplicate of #58, #55, #53

**Comment by osuleymanova** [comment] 2023-05-31 23:27
Hello @roumenh,

Thank you for reaching out to us and reporting this typo. The code snippet is updated:

![Screenshot 2023-05-31 at 4 14 51 PM](https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/86437155/bf239f8d-d29a-42fe-98bc-3428e69d73b1)

**Closed by osuleymanova** 2023-05-31 23:27 UTC
