### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by CodingHarang** [google-developer-training/basic-android-kotlin-compose-training-unscramble#64] opened 2023-02-27 14:07 UTC
![image](https://user-images.githubusercontent.com/95116599/221584623-b0d5ef13-3c43-4b83-93a7-6ae264155489.png)
at section 8, code snippet below description number 5, I think code should be change to
val currentWordCount: Int = 1,
val score: Int = 0

**Comment by osuleymanova** [comment] 2023-03-16 19:57
Duplicate of #61

**Comment by osuleymanova** [comment] 2023-05-31 23:24
Hello @CodingHarang,

Thank you for reaching out to us and reporting this typo. The code snippet is updated:

![Screenshot 2023-05-31 at 4 14 51 PM](https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/86437155/bf239f8d-d29a-42fe-98bc-3428e69d73b1)

**Closed by osuleymanova** 2023-05-31 23:24 UTC
