### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by majedamin974** [google-developer-training/basic-android-kotlin-compose-training-unscramble#81] opened 2023-04-09 15:16 UTC
In task 8 step No. 5, the instruction says to add a variable with name `currentWordCount` with initial value of `1`
but in the code snippet is not.

![snippet](https://user-images.githubusercontent.com/32139269/230780890-9b64a97f-f871-447e-8e1e-4bf4edd8d218.png)

**Comment by osuleymanova** [comment] 2023-04-13 00:02
Duplicate of #77, #75, #73, #69, #64, #61, #58, #53, #52.

**Comment by osuleymanova** [comment] 2023-05-31 23:22
Hello @majedamin974 ,

Thank you for reaching out to us and reporting this typo. The code snippet is updated:

![Screenshot 2023-05-31 at 4 14 51 PM](https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/86437155/ab533c2f-1b03-4e11-b224-381238a093be)

**Closed by osuleymanova** 2023-05-31 23:22 UTC
