### ISSUE TITLE
Android Basics: Viewmodel and State in Compose (update score and word count)

### ISSUE THREAD

**Issue by Masharo** [google-developer-training/basic-android-kotlin-compose-training-unscramble#53] opened 2023-02-07 09:58 UTC
![image](https://user-images.githubusercontent.com/44152085/217212303-cb92aefe-cd71-487a-8675-ed474a564e4c.png)

**Comment by osuleymanova** [comment] 2023-03-16 22:11
Duplicate of #52

**Comment by osuleymanova** [comment] 2023-05-31 23:26
Hello @Masharo,

Thank you for reaching out to us and reporting this typo. The code snippet is updated:

![Screenshot 2023-05-31 at 4 14 51 PM](https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/86437155/bf239f8d-d29a-42fe-98bc-3428e69d73b1)

**Closed by osuleymanova** 2023-05-31 23:26 UTC
