### ISSUE TITLE
Inconsistencies between text and code

### ISSUE THREAD

**Issue by Gamer2015** [google-developer-training/basic-android-kotlin-compose-training-unscramble#85] opened 2023-04-14 21:05 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-viewmodel-and-state

**In which task and step of the codelab can this issue be found?**
Task 8, Step 5

**Describe the problem**
The code is inconsistent with the text: 
The property currentWordCount is initialized to 0, but the text above specifies the currentWordCount to be initialized to 1.

Later in the codelab another variable is added to this class, which initializes score to 0 and currentWordCount to 1 instead, so I guess these should be the correct assignments

**Additional information**
<img width="1375" alt="Screenshot Task 8" src="https://user-images.githubusercontent.com/6293177/232153792-a453cbba-c8c3-4dfb-a931-a758c152e5ed.png">
Later in the codelab:
<img width="1396" alt="Screenshot Task 9" src="https://user-images.githubusercontent.com/6293177/232154682-3b6e3a06-f68c-403b-a8bd-6a96cd58f8a9.png">

**Comment by osuleymanova** [comment] 2023-04-19 23:22
Duplicate of #84, #81, #77, #75, #73, #69, #64, #61, #58, #53, #52.

**Closed** 2023-05-31 23:19 UTC
