### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by TommyOstrom** [google-developer-training/basic-android-kotlin-compose-training-unscramble#29] opened 2022-12-14 07:45 UTC
On page https://developer.android.com/codelabs/basic-android-kotlin-compose-viewmodel-and-state#6 it is not explained what value isGuessWrong should be given when calling GameLayout()
```
GameLayout(
   currentScrambledWord = gameUiState.currentScrambledWord,
   userGuess = gameViewModel.userGuess,
   onUserGuessChanged = { gameViewModel.updateUserGuess(it) },
   onKeyboardDone = { gameViewModel.checkUserGuess() },
  
)
```

**Comment by osuleymanova** [comment] 2022-12-14 18:49
Duplicate of #28

**Comment by osuleymanova** [comment] 2022-12-14 19:02
Hello @TommyOstrom,

Thanks for reaching out. Hopefully the screenshot below gives you an answer:

![Screen Shot 2022-12-14 at 11 00 33 AM](https://user-images.githubusercontent.com/86437155/207688691-d764caf1-ea44-4863-902e-946ba753975a.png)

**Closed by osuleymanova** 2022-12-14 19:02 UTC
