### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by dany0s** [google-developer-training/basic-android-kotlin-compose-training-unscramble#69] opened 2023-03-10 01:34 UTC
`val currentWordCount: Int = 0`  should be `val currentWordCount: Int = 1`

**Comment by osuleymanova** [comment] 2023-03-16 19:59
Duplicate of #64, #61

**Comment by osuleymanova** [comment] 2023-05-31 23:25
Hello @dany0s,
Thank you for reaching out to us and reporting this typo. The code snippet is updated:

![Screenshot 2023-05-31 at 4 14 51 PM](https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/86437155/bf239f8d-d29a-42fe-98bc-3428e69d73b1)

**Closed by osuleymanova** 2023-05-31 23:25 UTC
