### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by uosamuel** [google-developer-training/basic-android-kotlin-compose-training-unscramble#58] opened 2023-02-14 12:13 UTC
On the 5th step on this pathway link below;

 https://developer.android.com/codelabs/basic-android-kotlin-compose-viewmodel-and-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-viewmodel-and-state#7

The game UI state is given as this;

data class GameUiState(
   val currentScrambledWord: String = "",
   val currentWordCount: Int = 0,
   val score: Int = 1,
   val isGuessedWordWrong: Boolean = false,
)

but it should be this; just as step 5 says - "Add another variable for the count in the GameUiState. Call it currentWordCount and initialize it to 1"

data class GameUiState(
    val currentScrambledWord: String = "",
    val isGuessedWordWrong: Boolean = false,
    val score: Int = 0,
    val currentWordCount: Int = 1
)

**Comment by osuleymanova** [comment] 2023-03-16 20:07
Duplicate of #55

**Comment by osuleymanova** [comment] 2023-05-31 23:26
Hello @uosamuel,

Thank you for reaching out to us and reporting this typo. The code snippet is updated:

![Screenshot 2023-05-31 at 4 14 51 PM](https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/86437155/bf239f8d-d29a-42fe-98bc-3428e69d73b1)

**Closed by osuleymanova** 2023-05-31 23:26 UTC
