### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by iamlockon** [google-developer-training/basic-android-kotlin-compose-training-unscramble#18] opened 2022-11-04 02:11 UTC
There is a typo in the article:

## Actual
> 3. In the `GameScreen()` composable function, add lambda parameters for `onUserGuessChanged` and `onKeyboardDone`.

## Expected
> 3. In the `GameLayout()` composable function, add lambda parameters for `onUserGuessChanged` and `onKeyboardDone`.

## Link

https://developer.android.com/codelabs/basic-android-kotlin-compose-viewmodel-and-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-viewmodel-and-state#5:~:text=In%20the-,GameScreen,-()%20composable%20function

**Comment by osuleymanova** [comment] 2022-11-23 18:22
Duplicate of #17

**Comment by osuleymanova** [comment] 2022-11-23 22:53
This issue is closed as a duplicate of #17

**Comment by osuleymanova** [comment] 2022-12-09 19:40
Hello @iamlockon,

Thank you for reaching out to us and reporting this typo. It is fixed:

![Screen Shot 2022-12-09 at 11 38 57 AM](https://user-images.githubusercontent.com/86437155/206783790-83d0880d-b4ef-48ce-80b2-1b060ea474e2.png)

**Closed by osuleymanova** 2022-12-09 19:40 UTC
